# Generated by Django 4.2.6 on 2023-11-08 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapp', '0003_citiesforecast_msg'),
    ]

    operations = [
        migrations.AddField(
            model_name='citiesforecast',
            name='cities',
            field=models.ManyToManyField(to='weatherapp.forecast'),
        ),
    ]
