# Generated by Django 4.2.6 on 2023-11-08 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapp', '0004_citiesforecast_cities'),
    ]

    operations = [
        migrations.AddField(
            model_name='citiesforecast',
            name='api_key',
            field=models.CharField(default='0', max_length=200),
            preserve_default=False,
        ),
    ]
