# Generated by Django 4.2.6 on 2023-11-08 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapp', '0007_hourforecast_historicalforecast'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalforecast',
            name='msg',
            field=models.CharField(default='OK', max_length=200),
            preserve_default=False,
        ),
    ]
